border_color = "#0A0D13"
primary_bg_color = "#0A0D13"
secondary_bg_color = "#16191F"
disabled_bg_color = "#26292F"
accent_color = "#008FCF"
text_color = "#EEEEEE"
disabled_text_color = "#DDDDDD"
border_radius = 6
error_color = "#FF0000"
success_color = "#00FF00"
mention_color = "#FFFFDD"
dimmed_text_color = "#DDDDDD"