border_color = "#1E2531"
primary_bg_color = "#161B24"
secondary_bg_color = "#272D3A"
disabled_bg_color = "#4E566A"
accent_color = "#1D6AD5"
text_color = "#ECEEF3"
disabled_text_color = "#CDD2E0"
border_radius = 6
error_color = "#FF0000"
success_color = "#00FF00"
mention_color = "#FFFFDD"
dimmed_text_color = "#DDDDDD"